const THEME = {
  BACKGROUND: '#f6f5fa',
  COLOR: '#001524',
  COLOR_ALT: '#0F2C59',
  CTA: '#713ABE',
  ACCENT: '#FF9501',
}

const FONTS = {
  POPPINS: {
    THIN: 'Poppins_100Thin',
    THIN_ITALIC: 'Poppins_100Thin_Italic',
    EXTRA_LIGHT: 'Poppins_200ExtraLight',
    EXTRA_LIGHT_ITALIC: 'Poppins_200ExtraLight_Italic',
    LIGHT: 'Poppins_300Light',
    LIGHT_ITALIC: 'Poppins_300Light_Italic',
    REGULAR: 'Poppins_400Regular',
    REGULAR_ITALIC: 'Poppins_400Regular_Italic',
    MEDIUM: 'Poppins_500Medium',
    MEDIUM_ITALIC: 'Poppins_500Medium_Italic',
    SEMI_BOLD: 'Poppins_600SemiBold',
    SEMI_BOLD_ITALIC: 'Poppins_600SemiBold_Italic',
    BOLD: 'Poppins_700Bold',
    BOLD_ITALIC: 'Poppins_700Bold_Italic',
    EXTRA_BOLD: 'Poppins_800ExtraBold',
    EXTRA_BOLD_ITALIC: 'Poppins_800ExtraBold_Italic',
    BLACK: 'Poppins_900Black',
    BLACK_ITALIC: 'Poppins_900Black_Italic',
  },
}

const LANGUAGES = [
  'en-US',
  'nl-NL',
  'fr-FR',
  'de-DE',
  'es-ES',
  'it-IT',
  'pt-PT',
  'ca-ES',
  'ru-RU',
  'ja-JP',
  'zh-CN',
  'ar-SA',
  'hi-IN',
  'ko-KR',
  'tr-TR',
  'pl-PL',
  'cs-CZ',
  'sv-SE',
  'da-DK',
  'no-NO',
  'fi-FI',
  'el-GR',
  'he-IL',
  'hu-HU',
  'ro-RO',
  'th-TH',
  'id-ID',
  'ms-MY',
  'vi-VN',
  'tl-PH',
  'uk-UA',
  'bg-BG',
  'hr-HR',
  'sr-RS',
  'sk-SK',
  'sl-SI',
  'et-EE',
  'lv-LV',
  'lt-LT',
  'is-IS',
  'ga-IE',
  'cy-GB',
  'gl-ES',
  'eu-ES',
  'sq-AL',
  'mk-MK',
  'bs-BA',
  'hy-AM',
  'ka-GE',
  'uz-UZ',
  'tt-RU',
  'tg-TJ',
  'km-KH',
  'mn-MN',
  'ne-NP',
  'si-LK',
  'pa-IN',
  'ta-IN',
  'te-IN',
  'kn-IN',
  'ur-PK',
  'bn-BD',
  'th-TH',
  'lo-LA',
  'my-MM',
  'ka-KG',
  'ug-CN',
  'tm-TM',
  'ku-IQ',
  'fa-IR',
  'ps-AF',
  'dv-MV',
  'bh-IN',
  'mr-IN',
  'sa-IN',
  'kk-KZ',
  'ky-KG',
  'az-AZ',
  'be-BY',
]

const FEEDBACK_PROMPTS: FeedbackPrompt[] = [
  {
    lowerPercentage: 90,
    upperPercentage: 100,
    promptPool: [
      'Excellent pronunciation!',
      'Mastered it perfectly!',
      'Flawless pronunciation!',
      'Impressive! Near perfection!',
    ],
  },
  {
    lowerPercentage: 80,
    upperPercentage: 89,
    promptPool: [
      'Great job! Pronunciation on point!',
      'Fantastic work! Nearly perfect!',
      'Well done! Close to mastering!',
      'Excelling! Just a bit more!',
    ],
  },
  {
    lowerPercentage: 70,
    upperPercentage: 79,
    promptPool: [
      'Doing well! Keep refining!',
      'Good effort! More practice!',
      'Nice work! Solid and improving!',
      'Keep it up! Great strides!',
    ],
  },
  {
    lowerPercentage: 60,
    upperPercentage: 69,
    promptPool: [
      'Getting there! Focus on nuances.',
      'Nice try! Fine-tuning needed.',
      'On the right track! Work on it.',
      'Improvement evident! Keep practicing!',
    ],
  },
  {
    lowerPercentage: 50,
    upperPercentage: 59,
    promptPool: [
      'A bit more effort!',
      'Not bad! Keep practicing.',
      'Making progress! Refine sounds.',
      'Good start! Consistency pays off.',
    ],
  },
  {
    lowerPercentage: 40,
    upperPercentage: 49,
    promptPool: [
      'Making progress! Identify challenges.',
      'Keep it up! Focus on improvement.',
      'Solid effort! Pinpoint areas.',
      'On the journey! Consistent practice!',
    ],
  },
  {
    lowerPercentage: 30,
    upperPercentage: 39,
    promptPool: [
      'Room for improvement. Identify areas.',
      'Keep practicing! Growth with effort.',
      'Break it down. Master basics.',
      'Making strides! Build core skills.',
    ],
  },
  {
    lowerPercentage: 20,
    upperPercentage: 29,
    promptPool: [
      'Focus on basics. Fundamental sounds.',
      'A start! Core elements.',
      'Foundations first! Essential sounds.',
      'Identify basics! Building blocks.',
    ],
  },
  {
    lowerPercentage: 10,
    upperPercentage: 19,
    promptPool: [
      'Work to do. Start with basics.',
      'Keep practicing! Consistency helps.',
      'Foundational challenges. Step by step.',
      "Don't be discouraged! Building up.",
    ],
  },
  {
    lowerPercentage: 0,
    upperPercentage: 9,
    promptPool: [
      'Identified challenges. Start with basics.',
      "Don't worry, everyone starts. Build up.",
      'Foundational work. Address issues.',
      'Beginning! Work together for improvement.',
    ],
  },
]

export { FONTS, THEME, LANGUAGES, FEEDBACK_PROMPTS }
